### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by damwhit** [DrewBradley/mod_0_skills#1]
@DrewBradley solid work on this! Both your javascript basics and foundational knowledge of OOP look good! It's definitely clear to me based on your method naming exactly what and how you're going to affect an attribute(s). I'd just remind you to always name your methods as actions, so `work_overtime` might be a better name than `overtime` per that convention. But overall, super solid work! Keep it up!

**Comment by DrewBradley** [comment]
@damwhit Thank you for the feedback! I will work on verbifying my methods. I think I tend to want to make names as short as possible, but human-readability takes precedence. Thank you!
